// settings
export const OPEN_SETTINGS = 'OPEN_SETTINGS';
export const CLOSE_SETTINGS = 'CLOSE_SETTINGS';
export const OPEN_AVATAR_DIALOG = 'OPEN_AVATAR_DIALOG';
export const CLOSE_AVATAR_DIALOG = 'CLOSE_AVATAR_DIALOG';
export const OPEN_FEEDBACK_VIEW = 'OPEN_FEEDBACK_VIEW';
export const CLOSE_FEEDBACK_VIEW = 'CLOSE_FEEDBACK_VIEW';
export const OPEN_EDITOR_VIEW = 'OPEN_EDITOR_VIEW';
export const CLOSE_EDITOR_VIEW = 'CLOSE_EDITOR_VIEW';
export const SET_SELECTED_STUDENT = 'SET_SELECTED_STUDENT';
export const SET_SELECTED_BOT = 'SET_SELECTED_BOT';
export const SET_CODE_EDITOR_SETTINGS = 'SET_CODE_EDITOR_SETTINGS';
