// settings
export const OPEN_SETTINGS = 'OPEN_SETTINGS';
export const CLOSE_SETTINGS = 'CLOSE_SETTINGS';
export const OPEN_AVATAR_SETTINGS = 'OPEN_AVATAR_SETTINGS';
export const CLOSE_AVATAR_SETTINGS = 'CLOSE_AVATAR_SETTINGS';
